[project]
name = "hidex_module"
version = "1.2.0"
description = "MADSci Module for controlling the Hidex Sense Platereader"
authors = [
    {name = "Doga Ozgulbas", email="dozgulbas@anl.gov"},
    {name = "Ryan D. Lewis", email="ryan.lewis@anl.gov"},
    {name = "Tobias Ginsburg", email = "tginsburg@anl.gov"},
]
dependencies = [
    "pythonnet",
    "madsci.node_module~=0.8.0",
    "madsci.client~=0.8.0",
    "madsci.common~=0.8.0",
]
requires-python = ">=3.10,<3.14"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/AD-SDL/hidex_module"

######################
# Build Info + Tools #
######################
[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "ruff>=0.11.7",
    "pytest",
]
